services:
  mysql:
    image: mysql:8
    container_name: mysql-dock
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent" ]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      container_name: phpmyadmin-dock
      ports:
        - "8080:80"
      environment:
        - PMA_HOST=mysql
        - PMA_USER=root
        - PMA_PASSWORD=
      depends_on:
        - mysql

  discovery-service:
      build: ./discovery-service
      container_name: discovery-dock
      ports:
        - '8761:8761'
      healthcheck:
        test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
        interval: 10s
        retries: 4

  config-service:
      build: ./config-service
      container_name: config-dock
      ports:
        - '9999:9999'
      healthcheck:
        test: [ "CMD", "curl", "-f", "http://localhost:9999/actuator/health" ]
        interval: 10s
        retries: 4
      environment:
        - DISCOVERY_SERVICE_URL=http://discovery-dock:8761/eureka
      depends_on:
        discovery-service:
          condition: service_healthy

  client-service:
    build: ./client-service
    container_name: client-dock
    ports:
      - '8090:8090'
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-dock:8761/eureka
      - CONFIG_SERVICE_URL=http://config-dock:9999
    depends_on:
      config-service:
        condition: service_healthy
      mysql:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "echo", "healthy" ]
      interval: 10s
      retries: 3
      start_period: 20s


  product-service:
      build: ./product-service
      container_name: product-dock
      ports:
        - '8091:8091'
      healthcheck:
        test: [ "CMD", "curl", "-f", "http://localhost:8091/actuator/health" ]
        interval: 20s
        timeout: 10s
        retries: 6
        start_period: 40s
      environment:
        - DISCOVERY_SERVICE_URL=http://discovery-dock:8761/eureka
        - CONFIG_SERVICE_URL=http://config-dock:9999
      depends_on:
        config-service:
          condition: service_healthy
        mysql:
          condition: service_healthy

  order-service:
      build: ./order-service
      container_name: order-dock
      ports:
        - '8092:8092'
      healthcheck:
        test: [ "CMD", "curl", "-f", "http://localhost:8092/actuator/health" ]
        interval: 10s
        retries: 4
      environment:
        - DISCOVERY_SERVICE_URL=http://discovery-dock:8761/eureka
        - CONFIG_SERVICE_URL=http://config-dock:9999
      depends_on:
        config-service:
          condition: service_healthy
        client-service:
          condition: service_healthy
        product-service:
          condition: service_healthy
        mysql:
          condition: service_healthy

  ### PostgreSQL with pgvector Support ###
  postgresql:
    container_name: vectordb
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: mehdi
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: vectordb
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "2020:5432"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U mehdi -d vectordb" ]
      interval: 10s
      timeout: 5s
      retries: 5

  llm-service:
    build: ./llm-service
    container_name: llm-dock
    ports:
      - '2222:2222'
    expose:
      - '2222'
    healthcheck:
      test: [ "CMD","curl","-f", "http://localhost:2222/actuator/health" ]
      interval: 15s
      timeout: 20s
      retries: 8
      start_period: 120s
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-dock:8761/eureka
      - CONFIG_SERVICE_URL=http://config-dock:9999
    depends_on:
      postgresql:
        condition: service_healthy
      config-service:
        condition: service_healthy

  gateway-service:
    build: ./gateway-service
    container_name: gateway-dock
    ports:
      - '8887:8887'
    expose:
      - '8887'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8887/actuator/health" ]
      interval: 10s
      timeout: 20s
      retries: 10
      start_period: 60s
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-dock:8761/eureka
      - CONFIG_SERVICE_URL=http://config-dock:9999
    depends_on:
      order-service:
        condition: service_healthy

networks:
  microservices-net:
    driver: bridge

volumes:
  postgres:
  mysql-data:


